### ISSUE TITLE
Problems transferring from trust wallet 

### ISSUE THREAD

**Issue by drvoolittle** [TrustWallet/trust-wallet-android#139]
Hi,  
I recently transferred some CANYA coins from kucoin to my trust wallet.  It amount of coins would temporarily show up and disappear.  When I try to transfer back to kucoin, I get a message that says I habe insufficient funds. Can you help me please? Thank you

**Comment by michaelScoff** [comment]
@drvoolittle Make sure you have ETH on your wallet to pay a gas fee.

**Comment by michaelScoff** [comment]
@madcake @maratsubkhankulov

**Comment by maratsubkhankulov** [comment]
Hello @drvoolittle this message usually indicates that you have insufficient ether balance in your wallet. Verify that the "network fee" in the send confirmation screen is less than the ether balance in your wallet.
