### ISSUE TITLE
Only the 3 first wallet transactions is showing?

### ISSUE THREAD

**Issue by aliamid93** [TrustWallet/trust-wallet-android#144]
On the "main-page", where you see a list of all the wallet activity, I can only see the 3 first transactions in my wallet.

All newer transactions are not showing up at all. I does not help to update or close/open the app.

**Comment by michaelScoff** [comment]
What’s your wallet address?

**Comment by aliamid93** [comment]
https://etherscan.io/address/0x55b0081dca2e2b4b290d291e441b067c5a632463 and I can only see the two transactions from 9 days ago and the one from 3 days ago

**Comment by michaelScoff** [comment]
@aliamid93 can you refresh again? 

I see that API returns correct number of transactions from here: https://api.trustwalletapp.com/transactions?address=0x55b0081dca2e2b4b290d291e441b067c5a632463

@madcake @maratsubkhankulov can you take a look at this issue it 's related to Android itself?

**Comment by aliamid93** [comment]
@michaelScoff It does show the correct amount now. I looked at the appstore and saw that there was an update for the app. I did update it, and just checked it after you wrote and it shows all the transactions right now.

Thanks for the help!

**Comment by michaelScoff** [comment]
@aliamid93 oh nice! I'm closing this now then.
