### ISSUE TITLE
Contacts list

### ISSUE THREAD

**Issue by Narragansett** [TrustWallet/trust-wallet-android#17]
Allow user to send/request against addresses pulled from a contact list. Text entry or QR codes are okay, better if they can be stored against contacts and allow use of friendly wallet names after that.

**Comment by maratsubkhankulov** [comment]
Do you mean having ability to configure a contact list with their names and addresses?

**Comment by Narragansett** [comment]
Two options -
a. Request user permission to tap into existing contact and add an ethereum wallet attribute
b. Clone it with just the name(s) and create a mirror wallet, one you could reclone if you add new contacts
c. Create a dictionary like a parallel wallet where user could enter contact name and their wallet address once
Okay, maybe that was three.  When I want to send/request money I'd like a friendly way to recall a contacts address without having to cut-paste or scan their wallet address.

Many social and financial apps request access to the contact list for this. Just need an extra attr for wallet address.

**Comment by Narragansett** [comment]
The need is to maintain a list of contact names and send/receive to the contact name rather than having to enter the actual wallet address.

**Comment by maratsubkhankulov** [comment]
@Narragansett thank you for your suggestions. I'm going to close this issue for now as it's not a priority for Trust for the foreseeable future and we can't allow scope creep at this stage. We appreciate your input.
