### ISSUE TITLE
Allow send of fractional ether

### ISSUE THREAD

**Issue by Narragansett** [TrustWallet/trust-wallet-android#20]
Its common to send fractional ether. Its also necessary since ether price is so high. trust-wallet-ios allows fractional. I removed the limit locally and it works fine. Request for adoption.

**Comment by maratsubkhankulov** [comment]
yes, this should allow <1 ETH transactions. Will be in the next release.

**Comment by maratsubkhankulov** [comment]
Please update to 1.3.5
