### ISSUE TITLE
Add Oracles network support

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-android#25]
Based on https://github.com/TrustWallet/trust-wallet-ios/pull/80

**Comment by michaelScoff** [comment]
Keep it in the PR, until we ready to go on this! 

Point to test network, until we have final endpoint for the main Oracles network chain

**Comment by maratsubkhankulov** [comment]
Sure, starting work on this tonight.

**Comment by maratsubkhankulov** [comment]
https://github.com/TrustWallet/trust-wallet-android/commit/bdfdabedf66ce75880455577c7e9bb92f201f878
https://github.com/TrustWallet/trust-wallet-android/commit/c24263176d7438a494dd17ed283e3ff50ddd44c0
https://github.com/TrustWallet/trust-wallet-android/commit/4127a7442b0ac27a01fb75ee1ef8170059b94857
https://github.com/TrustWallet/trust-wallet-android/commit/58fb3cc72e2897b3e12bd659f7078646cef46bc9
