### ISSUE TITLE
Hitting back after setting up backup wallet takes me back to password fill in screen

### ISSUE THREAD

**Issue by tomglynch** [TrustWallet/trust-wallet-android#26]
Steps to reproduce:

1. Install app
2. Start it up
3. When it requests to create backup hit okay.
4. Add passwords
5. Press okay. 
6. Switch screens in the app
7. Press back multiple times
8. Goes back to the backup wallet password page with passwords filled in

At this point I am not sure what happens. If you edit the password you will have 2 backups? Just seems a bit odd that it goes back to this.

**Comment by michaelScoff** [comment]
@tomglynch thanks, Tom! I will make changes to avoid hitting back button for those views.

I don't think it's a security concert since you can export the private key from the settings.

Thanks for reporting!

**Comment by maratsubkhankulov** [comment]
@tomglynch thanks for logging the issue. What is the title of the screen you see after you press ok in step 5?

**Comment by tomglynch** [comment]
Yeah fair enough about it not being a security concern. 

After step 5 you share it, then it takes you to the Send screen.

**Comment by maratsubkhankulov** [comment]
@tomglynch happy to report that this issue was fixed in https://github.com/TrustWallet/trust-wallet-android/issues/38. Please update the app.
