### ISSUE TITLE
[Android] Integrate keystore

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-android#33]
https://developer.android.com/training/articles/keystore.html

**Comment by maratsubkhankulov** [comment]
@rip32700 didn't we intentionally not use the keystore for lack of security?

**Comment by michaelScoff** [comment]
https://github.com/breadwallet/breadwallet-android/blob/832f1d4de56d76cd273ee61f5d3b84b682c842a8/app/src/main/java/com/breadwallet/tools/security/BRKeyStore.java

**Comment by michaelScoff** [comment]
@maratsubkhankulov @madcake is this integrated now?

**Comment by maratsubkhankulov** [comment]
https://github.com/TrustWallet/trust-wallet-android/commit/44850ed5cef02cdd60e7d5a83672f1100a43937f
