### ISSUE TITLE
Problem sending ETH out of app

### ISSUE THREAD

**Issue by riskmgr1** [TrustWallet/trust-wallet-android#42]
error signing:
java.langnumberformatexeception:invalid
long: "1400000000000000000000"

Have tried sending to multiple addresses and get this error every time.

**Comment by maratsubkhankulov** [comment]
Thanks for logging the issue. What are you setting your gas limit and price to? Are you sending tokens?

**Comment by riskmgr1** [comment]
Have tried various gas limit settings and none work. No tokens, only ETH.

**Comment by maratsubkhankulov** [comment]
Ok ETA 4 hours from now.

**Comment by riskmgr1** [comment]
thanks for the fast support

**Comment by maratsubkhankulov** [comment]
Tested using version 1.3.15 (19). Transaction successful. Can you please confirm your android version and Trust version - go to settings > scroll to bottom.

**Comment by maratsubkhankulov** [comment]
Issue has been fixed. Please update to version 1.3.16 (20) once it has propagated to the play store.

**Comment by michaelScoff** [comment]
@riskmgr1 can you verify it?

**Comment by riskmgr1** [comment]
Yes, I am no longer having the issue after update.
