### ISSUE TITLE
Wallet password generation

### ISSUE THREAD

**Issue by Krocks** [TrustWallet/trust-wallet-android#43]
Please use https://developer.android.com/reference/java/security/SecureRandom.html with enough entropy (256) instead of UUID.randomUUID(). 

Also according to Android code style (https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md) key length (256) should be treated as constant

P.S. As a change request password generation should also be moved to class responsible for password managing (KS.java) (it's only my opinion, it's not a bug and you may think in another way)

**Comment by michaelScoff** [comment]
@madcake @maratsubkhankulov  is this closed?

**Comment by maratsubkhankulov** [comment]
yes, https://github.com/TrustWallet/trust-wallet-android/commit/40d69c0755a256f48a73d70b4cdff6243cc64d5d
