### ISSUE TITLE
Update app description

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-android#45]
from https://github.com/TrustWallet/trust-wallet-ios/blob/master/fastlane/metadata/en-US/description.txt, and change `iOS` to `Android`

find a way to use this keywords as well https://github.com/TrustWallet/trust-wallet-ios/blob/master/fastlane/metadata/en-US/keywords.txt

**Comment by michaelScoff** [comment]
Make sure Fastlane integrated for this change!

**Comment by maratsubkhankulov** [comment]
https://github.com/TrustWallet/trust-wallet-android/commit/31302867524fdfb10394409a69c84b641814808f
