### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by bahek332** [TrustWallet/trust-wallet-android#62]
Keystore import is not working. No file select dialogue.
Miui 9, Android 7

**Comment by michaelScoff** [comment]
What error do you get?

**Comment by bahek332** [comment]
No error at all. Just blank field. And field for password. When I tap on it, I can just type text, but how to upload json :)

**Comment by michaelScoff** [comment]
oh, you need to put the content of your file into that field and you should be good to go!

@maratsubkhankulov can you add support to pick a file from the system?

**Comment by maratsubkhankulov** [comment]
> support to pick a file from the system?

Certainly.

And yes, right now just copy JSON into the field.

Marat
