### ISSUE TITLE
Implement fingerprint authentication on app open

### ISSUE THREAD

**Issue by samlin86** [TrustWallet/trust-wallet-android#86]
For security, allow the user to turn on fingerprint reader protection of the app, or alternatively, a passcode.

**Comment by rip32700** [comment]
Hi @samlin86 , this is currently under development and will be added in the next version

**Comment by michaelScoff** [comment]
Dup of https://github.com/TrustWallet/trust-wallet-android/issues/12.

@samlin86 would you like to contribute to Trust app? We have couple of things to work on iOS and Android

**Comment by samlin86** [comment]
Oh sorry, totally didn't see that one. Looks like #66 has already implemented this recently and is in review.

**Comment by michaelScoff** [comment]
@samlin86 yeah, we just re-wrote the whole app to MVVM, doing final testing and then full focus on new features! pin code the first one to merge!
