### ISSUE TITLE
Crash - No address associated with hostname

### ISSUE THREAD

**Issue by maratsubkhankulov** [TrustWallet/trust-wallet-android#96]
Steps to reproduce:
1. Turn off internet connectivity
2. Switch network
3. Go to transaction list -> open send
4. Return to transaction list
5. Repeat 2-4 several times

`01-08 20:45:31.965 15772-15911/com.wallet.crypto.trustapp W/System.err: io.reactivex.exceptions.UndeliverableException: java.net.UnknownHostException: Unable to resolve host "api.trustwalletapp.com": No address associated with hostname
01-08 20:45:31.965 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
01-08 20:45:31.965 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:604)
01-08 20:45:31.965 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:665)
01-08 20:45:31.966 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onError(SingleToFlowable.java:68)
01-08 20:45:31.966 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onError(ObservableSingleSingle.java:95)
01-08 20:45:31.966 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onError(ObservableDoOnEach.java:119)
01-08 20:45:31.967 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
01-08 20:45:31.967 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
01-08 20:45:31.967 15772-15911/com.wallet.crypto.trustapp W/System.err:     at com.wallet.crypto.trustapp.service.BlockExplorerClient$ApiErrorOperator$1.onError(BlockExplorerClient.java:98)
01-08 20:45:31.967 15772-15911/com.wallet.crypto.trustapp W/System.err:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:55)
01-08 20:45:31.967 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10955)
01-08 20:45:31.968 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.internal.operators.observable.ObservableLift.subscribeActual(ObservableLift.java:57)
01-08 20:45:31.968 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10955)
01-08 20:45:31.968 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
01-08 20:45:31.968 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10955)
01-08 20:45:31.968 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
01-08 20:45:31.969 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
01-08 20:45:31.969 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
01-08 20:45:31.969 15772-15911/com.wallet.crypto.trustapp W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
01-08 20:45:31.969 15772-15911/com.wallet.crypto.trustapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-08 20:45:31.969 15772-15911/com.wallet.crypto.trustapp W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
01-08 20:45:31.969 15772-15911/com.wallet.crypto.trustapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-08 20:45:31.969 15772-15911/com.wallet.crypto.trustapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-08 20:45:31.969 15772-15911/com.wallet.crypto.trustapp W/System.err:     at java.lang.Thread.run(Thread.java:764)
01-08 20:45:31.970 15772-15911/com.wallet.crypto.trustapp W/System.err: Caused by: java.net.UnknownHostException: Unable to resolve host "api.trustwalletapp.com": No address associated with hostname
01-08 20:45:31.970 15772-15911/com.wallet.crypto.trustapp W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
01-08 20:45:31.970 15772-15911/com.wallet.crypto.trustapp W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
01-08 20:45:31.970 15772-15911/com.wallet.crypto.trustapp W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:787)
01-08 20:45:31.970 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.Dns$1.lookup(Dns.java:39)
01-08 20:45:31.970 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
01-08 20:45:31.971 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
01-08 20:45:31.971 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
01-08 20:45:31.971 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:213)
01-08 20:45:31.971 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
01-08 20:45:31.971 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
01-08 20:45:31.971 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
01-08 20:45:31.971 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-08 20:45:31.971 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-08 20:45:31.971 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
01-08 20:45:31.971 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-08 20:45:31.971 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-08 20:45:31.971 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
01-08 20:45:31.972 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-08 20:45:31.972 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
01-08 20:45:31.972 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-08 20:45:31.972 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-08 20:45:31.972 15772-15911/com.wallet.crypto.trustapp W/System.err:     at com.wallet.crypto.trustapp.util.LogInterceptor.intercept(LogInterceptor.java:63)
01-08 20:45:31.972 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-08 20:45:31.972 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-08 20:45:31.972 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
01-08 20:45:31.972 15772-15911/com.wallet.crypto.trustapp W/System.err:     at okhttp3.RealCall.execute(RealCall.java:77)
01-08 20:45:31.972 15772-15911/com.wallet.crypto.trustapp W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
01-08 20:45:31.972 15772-15911/com.wallet.crypto.trustapp W/System.err:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)`

**Comment by madcake** [comment]
#102
